image: docker/compose:latest

services:
  - docker:dind

stages:
    - build
    - test

build_images:
    stage: build
    script:
        - "docker-compose -f docker-compose.yml -f docker-compose.override.prod.yml build"

test:
    stage: test
    script: 
        - "docker-compose -f docker-compose-tests.yml api build"
        - "docker run api:test dotnet test"

