image: totsamiynixon/dotnet-nodejs:latest

stages:
    - build
    - test

build_api:
    stage: build
    script:
        - "dotnet build server/ClearSkyMaps.Server.sln"

build_pwa:
    stage: build
    script:
        - "cd ./client/ionic-pwa && npm install"
        - "ionic build --prod --platform=browser"

test:
    stage: test
    script: 
        - "dotnet test ./server/ClearSkyMaps.Server.sln"
