image:
  name: docker/compose:1.23.2
  entrypoint: [""]

services:
  - docker:dind

stages:
    - build
    - test


before_script:
  - docker info

build_images:
    stage: build
    script:
        - "docker-compose -f docker-compose.yml -f docker-compose.override.prod.yml build"

test:
    stage: test
    script: 
        - "docker-compose -f docker-compose-tests.yml build api"
        - "docker run api:test dotnet test"

