version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: msbuild src/ClearSkyMaps.sln
  - branches:
      only:
        - production
    environment:
      DEPLOY_STAGE: Production
    build_script:
      - cmd: msbuild src/ClearSkyMaps.sln /p:DeployOnBuild=true /p:PublishProfile=PublishToFolderProfile
    artifacts:
      - path: ./src/release
        name: ProductionRelease
        type: Zip
    deploy_script:
      - cmd: powershell -file deploy.ps1 -artifactPath ProductionRelease.zip
  - branches:
      only:
        - staging
    environment:
      DEPLOY_STAGE: Staging
    build_script:
      - cmd: msbuild src/ClearSkyMaps.sln /p:DeployOnBuild=true /p:PublishProfile=PublishToFolderProfile
    artifacts:
      - path: ./src/release
        name: StagingRelease
        type: Zip
    deploy_script:
      - cmd: powershell -file deploy.ps1 -artifactPath StagingRelease.zip

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
clone_depth: 1
test_script:
  - cmd: dotnet test ./UnitTests
