version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build server/ClearSkyMaps.sln
      - cmd: npm run build --prefix client/mobile-spa
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      NOVE_ENV: production
    build_script:
      - cmd: dotnet publish server/ClearSkyMaps.sln -c Release -o ../../release
      - cmd: npm run build --prefix client/mobile-spa
      - cmd: xcopy client\mobile-spa\www release\wwwroot\spa /E /H /I
    artifacts:
      - path: ./release
        name: WebAppProd_{build}
        type: Zip
    deploy_script:
      - cmd: powershell -file appveyor.deploy.ps1 -artifactName WebAppProd_{build}.zip -domain %PRODUCTION_DOMAIN%
  - branches:
      only:
        - staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      NOVE_ENV: staging
    build_script:
      - cmd: dotnet publish server/ClearSkyMaps.sln -c Release -o ../../release
      - cmd: npm run build --prefix client/mobile-spa
      - cmd: xcopy client\mobile-spa\www release\wwwroot\spa /E /H /I
    artifacts:
      - path: ./release
        name: WebAppStaging_${build}
        type: Zip
    deploy_script:
      - cmd: powershell -file appveyor.deploy.ps1 -artifactName WebAppStaging_{build}.zip -domain %STAGING_DOMAIN%
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore ./server/ClearSkyMaps.sln
  - cmd: cd ./client/mobile-spa && npm install
clone_depth: 1
test:
  assemblies:
    - '**\*.Tests.dll'
