version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build server/ClearSkyMaps.Server.sln
      - cmd: npm run build-prod --prefix client/mobile-spa
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      NOVE_ENV: production
    build_script:
      - cmd: dotnet publish server/ClearSkyMaps.Server.sln -c Release -o ../../release/api -r win81-x64
      - cmd: npm run build-prod --prefix client/mobile-spa
      - cmd: xcopy client\mobile-spa\www release\web-client /E /H /I
    artifacts:
      - path: ./release/api
        name: APIProduction
      - path: ./release/web-client
        name: WebClientProduction
    deploy:
      - provider: WebDeploy
        server: https://$(MAIN_DOMAIN):8172/MsDeploy.axd
        website: $(PRODUCTION_API_SITE_NAME)
        username: $(WEB_DEPLOY_USERNAME)
        password: $(WEB_DEPLOY_PASSWORD)
        ntlm: false
        remove_files: true
        artifact: APIProduction
      - provider: WebDeploy
        server: https://$(MAIN_DOMAIN):8172/MsDeploy.axd
        website: $(PRODUCTION_SITE_NAME)
        username: $(WEB_DEPLOY_USERNAME)
        password: $(WEB_DEPLOY_PASSWORD)
        ntlm: false
        remove_files: true
        artifact: WebClientProduction
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      NOVE_ENV: staging
    build_script:
      - cmd: dotnet publish server/ClearSkyMaps.Server.sln -c Release -o ../../release/api -r win81-x64
      - cmd: npm run build-prod --prefix client/mobile-spa
      - cmd: xcopy client\mobile-spa\www release\web-client /E /H /I
    artifacts:
      - path: ./release/api
        name: APIStaging
      - path: ./release/web-client
        name: WebClientStaging
    deploy:
      - provider: WebDeploy
        server: https://$(MAIN_DOMAIN):8172/MsDeploy.axd
        website: $(STAGING_API_SITE_NAME)
        username: $(WEB_DEPLOY_USERNAME)
        password: $(WEB_DEPLOY_PASSWORD)
        ntlm: false
        remove_files: true
        artifact: APIStaging
      - provider: WebDeploy
        server: https://$(MAIN_DOMAIN):8172/MsDeploy.axd
        website: $(STAGING_SITE_NAME)
        username: $(WEB_DEPLOY_USERNAME)
        password: $(WEB_DEPLOY_PASSWORD)
        ntlm: false
        remove_files: true
        artifact: WebClientStaging
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore ./server/ClearSkyMaps.Server.sln
  - cmd: cd ./client/mobile-spa && npm install
clone_depth: 1
test:
  assemblies:
    - '**\*.Tests.dll'
