version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build:
      project: server/ClearSkyMaps.sln
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    artifacts:
      - path: ./server/release
        name: ProductionRelease
        type: Zip
    deploy_script:
      - cmd: powershell -file deploy.ps1 -artifactPath server/ProductionRelease.zip
  - branches:
      only:
        - staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    artifacts:
      - path: ./src/release
        name: StagingRelease
        type: Zip
    deploy_script:
      - cmd: powershell -file deploy.ps1 -artifactPath server/StagingRelease.zip

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore ./server/ClearSkyMaps.sln
clone_depth: 1
test:
  assemblies:
    - '**\*.Tests.dll'
