version: "1.0.{build}"
image: Visual Studio 2017
branches:
  only:
    - master
    - staging
    - production
for:
  - branches:
      only:
        - master
    build_script:
      - cmd: dotnet build
  - branches:
      only:
        - production
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RELEASE_STAGE: production
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    artifacts:
      - path: ./release
        name: ProductionRelease
        type: Zip
    deploy_script:
      - cmd: dotnet run --project deploy/WebDeployClient.csproj ProductionRelease.zip
  - branches:
      only:
        - staging
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      RELEASE_STAGE: staging
    build_script:
      - cmd: dotnet publish -c Release -o ../release
    artifacts:
      - path: ./release
        name: StagingRelease
        type: Zip
    deploy_script:
      - cmd: dotnet run --project deploy/WebDeployClient.csproj StagingRelease.zip

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  - cmd: dotnet restore
clone_depth: 1
test_script:
  - cmd: dotnet test ./UnitTests
