version: "3.4"
services:
    api:
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - DATABASE_DOMAIN=sql.data
        - DATABASE_USER_PASSWORD=P4ss-W0rd!
        - DATABASE_USER_ID=sa
      image: csm_api:test
      build: 
          context: ./src/Services/Readings
          target: unittest
          dockerfile: ./API/Dockerfile